### ISSUE TITLE
大佬能做全屏沉浸式就好了

### ISSUE THREAD

**Issue by yxj1028530975** [Ahuijava1/word_project#4]
如题

**Comment by yxj1028530975** [comment]
把生词本加入到背词本这个功能。

**Comment by Ahuijava1** [comment]
> 把生词本加入到背词本这个功能。

这个应该会做，到时应该也会支持上传生词本的功能

**Comment by Ahuijava1** [comment]
沉浸式是所有页面还是阅读页面

**Comment by yxj1028530975** [comment]
阅读页面，把浏览器全屏就可以了，嗯，我用的是pc端的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ahui"<notifications@github.com&gt;; 
发送时间: 2020年12月25日(星期五) 中午11:02
收件人: "Ahuijava1/word_project"<word_project@noreply.github.com&gt;; 
抄送: "1028530975"<1028530975@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Ahuijava1/word_project] 大佬能做全屏沉浸式就好了 (#4)





 
沉浸式是所有页面还是阅读页面

**Comment by Ahuijava1** [comment]
// 全屏，百度的，刚刚试了可以
//进入全屏
    function enterFullScreen() {
        var de = document.documentElement;
        if (de.requestFullscreen) {
            de.requestFullscreen();
        } else if (de.mozRequestFullScreen) {
            de.mozRequestFullScreen();
        } else if (de.webkitRequestFullScreen) {
            de.webkitRequestFullScreen();
        }
    }
    //退出全屏
    function exitFullScreen() {
        var de = document;
        if (de.exitFullscreen) {
            de.exitFullscreen();
        } else if (de.mozCancelFullScreen) {
            de.mozCancelFullScreen();
        } else if (de.webkitCancelFullScreen) {
            de.webkitCancelFullScreen();
        }
    }

**Comment by yxj1028530975** [comment]
是的，F11就可以了，麻烦你了

**Comment by Ahuijava1** [comment]
> 是的，F11就可以了，麻烦你了

这个项目的前端要用vue重构了，以前的应该会大改
